### ISSUE TITLE
`from_proto()` expects a `cotevent`, not a `takmessage`

### ISSUE THREAD

**Issue by mrtnlrsn** [dfpc-coe/node-CoT#32]
From the description I would expect, that `from_proto()` could decode an ATAK message.
I have tried decoding a message from an android tablet running ATAK, but that message uses the `TakMessage` protobuf format, not the `CotEvent` that the code expects.

```
    /**
     * Parse an ATAK compliant Protobuf to a JS Object
     */
    static from_proto(raw: Uint8Array, version = 1): CoT {

```

After replacing cotmessage with takmessage in `cot.ts` decoding works as expected.

(nice library otherwise)

**Comment by ingalls** [comment]
@mrtnlrsn Good catch. I haven't gotten around to implementing the Protobuf support in CloudTAK yet so haven't used this on anything other than test fixtures. I'll fix this and cut a new release today.
