### ISSUE TITLE
v12.5.1 is not working

### ISSUE THREAD

**Issue by mrtnlrsn** [dfpc-coe/node-CoT#44]
Running with version that version yields:
```
node:internal/modules/esm/resolve:342
  return new ERR_INVALID_PACKAGE_TARGET(
         ^

Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "dist/index.js" defined in the package config /home/mla/work/argos/js_src/mdc2_tak_service/node_modules/@tak-ps/node-cot/package.json imported from /home/mla/work/argos/js_src/mdc2_tak_service/js_src/services/takReceiverService.js; targets must start with "./"
```

node,js version 20.17.0
tsc version 5.6.2

Error is also higlighted by just opening the project in vscode.

Prepending the export paths with `./` seems to fix it.

**Comment by ingalls** [comment]
@mrtnlrsn Strange, I deployed this to production without incident, It must have been using the old style exports. 

Fixed both this and the group issue in v12.5.2. Thanks as always for the reports!
